Feature/server/map display/api fetch locations
csci-499-fa24/AccessAbleNYC pull request #12
Opened 2024-10-03 18:58 UTC by perlaescano

## Description
- Added a new API endpoint `/locations` to fetch all_location data from the MongoDB database.
- Created the `Location` model in `server/models/location.model.js` to define the schema for locations.
- Implemented the location route in `server/routes/location.route.js` to handle API requests.
- Updated the `Home` component in `Home.jsx` to fetch location data.
- Corrected some spelling mistakes in the user route (`server/routes/user.route.js`).

## What's in this change?
- API endpoint to fetch location data.
- New Mongoose model for handling location data (`Location`).
- Backend route for fetching locations from the `all_locations` collection.
- Integration with the frontend to fetch and display location data in the `Home` component.

## Testing
- Tested the `/locations` endpoint using Postman to verify data retrieval from MongoDB.
- Verified that the frontend correctly fetches and displays location data in the console.
- Checked the integration between the frontend and backend locally.
- Deployed committed changes to Render and verified functionality on the live environment.

2024-10-03 20:42 UTC, JacksonZ2003 requested changes
Good work! Have a look at my two comments!

2024-10-03 20:42 UTC, JacksonZ2003 commented on server/routes/location.route.js
> +router.get('/', async (req, res) => {
Please make a get request on route /locations

2024-10-03 20:42 UTC, JacksonZ2003 commented on client/src/pages/Home.jsx
> -import '../style/Home.css';
Add back the styling sheet instead delete the unnecessary css class indicator.

2024-10-03 21:05 UTC, keunsublee commented on server/models/location.model.js
will need address and multipolygon if we want to use data with no lat/lon (Sports, Athletic Facilities), we could drop these though

2024-10-03 21:23 UTC, keunsublee approved these changes

2024-10-04 00:09 UTC, perlaescano commented on server/models/location.model.js
yes I will address that in another task/branch setup (Server/Map-Display: Setup geospatial queries)

2024-10-04 01:20 UTC, JacksonZ2003 approved these changes
Good JOB!

2024-10-04 01:20 UTC, merged